/* ─────────────────────────────────────────────────────────────
   data.js — everything hand-written lives here.
   Edit freely; js/media.js is generated and should not be edited.
   ───────────────────────────────────────────────────────────── */

window.SHOW = {
  title: 'Shivani & Premal',
  tagline: 'a love story in five seasons',
  year: '2023 – 2026',
  rating: 'Rated L · for Love',
  synopsis:
    'From a first hello in Toronto to a goodbye at the airport — and everything that came after. ' +
    'Temple mornings, Navratri nights, a graduation, one birthday that deserved better, and a thousand ordinary days that turned out to be the whole point.',
  cast: ['Shivani ♡', 'Premal'],
  creator: 'Fate, with a little help from Toronto',
  genres: ['Romance', 'Slice of Life', 'Feel-Good', 'Based on a True Story'],
  // Netflix's "This show is:" line
  moods: ['Heartfelt', 'Romantic', 'Feel-Good'],
  // Maturity box + reasons, as Netflix prints them
  maturity: 'L',
  advisories: 'late-night drives, too much pizza, happy tears',
  // Poster used on the details sheet
  poster: 'images/20250803_194808.jpg',
  // Closing card photo
  finalePhoto: 'images/20260423_171132.jpg',
};

/* Billboard features — the home page rotates through these every few seconds.
   kind: 'series' (the show itself), 'episode' (an episode by date), 'top' (a Top 10 moment by file), 'season' (by number).
   `video` plays muted when its orientation matches the screen; otherwise the still is shown. */
window.FEATURES = [
  { kind: 'series',  tag: 'Series', trailer: true, still: 'images/s_20260924_120000_15.jpg', video: 'videos/s_20260924_114730_1.mp4' },
  { kind: 'episode', tag: 'New Episode', day: '2026-09-26' },
  { kind: 'top',     tag: '#1 in Top 10', key: '20260423_171132.jpg' },
  { kind: 'season',  tag: 'Prequel', n: 0 },
];

/* Billboard highlights — a pool of loglines. Each time the site opens,
   the billboard picks a fresh mix (avoiding the ones shown last time), with a random
   photo from that episode and a random filmy badge. Add as many as you like:
   { day: 'YYYY-MM-DD', line: '…' } for an episode, or { season: n, line: '…' } for a season. */
window.HIGHLIGHT_BADGES = ['Fan Favourite', 'Critically Acclaimed', 'Top Pick for Shivani', 'Must Watch', 'Award-Winning', 'Feel-Good Pick', 'Binge-Worthy', 'Rewatchable'];
window.HIGHLIGHTS = [
  { season: 0,          line: 'Before there was an us, there were these days.' },
  { day: '2023-12-31',  line: 'A new year, the same smile.' },
  { day: '2024-05-11',  line: 'Dinner high above the city, somewhere near the stars.' },
  { day: '2024-07-21',  line: 'A wall of flowers, and the prettiest one standing in front of it.' },
  { day: '2024-08-25',  line: 'Rides, lights, and the very first rush of something new.' },
  { day: '2024-08-26',  line: 'Temple bells, and the first prayer they share.' },
  { day: '2024-09-30',  line: 'One coffee, one slice of cake, and the start of everything.' },
  { day: '2024-10-12',  line: 'Cocktails in smoke, and a story in her eyes.' },
  { day: '2024-10-14',  line: 'Dandiya, dhol, and glances that keep finding each other.' },
  { day: '2024-11-03',  line: 'Her car, her road. A grand entrance.' },
  { day: '2024-12-14',  line: 'A royal date at the Royal York.' },
  { day: '2024-12-15',  line: 'City nights, hand in hand.' },
  { day: '2025-01-05',  line: 'The roar of the falls, and one name on his mind.' },
  { day: '2025-01-09',  line: 'She\'s in Mumbai, he\'s in Toronto. Even the distance is cinematic.' },
  { day: '2025-01-25',  line: 'An airport, a bouquet of roses, and a long wait. Straight out of a movie.' },
  { day: '2025-02-07',  line: 'Smiles all night. A hit from the first scene.' },
  { day: '2025-04-05',  line: 'Home, quiet, and just the two of them.' },
  { day: '2025-04-12',  line: 'A perfect date, worth every minute.' },
  { day: '2025-04-26',  line: 'One plate, two spoons, and a very sweet argument.' },
  { day: '2025-05-23',  line: 'Tonight\'s leading lady steals every scene.' },
  { day: '2025-05-27',  line: 'A degree in her hands, and pride in his eyes.' },
  { day: '2025-06-29',  line: 'The pizza was just an excuse.' },
  { day: '2025-07-06',  line: 'A long walk, a cool breeze, and the perfect person.' },
  { day: '2025-07-12',  line: 'A small town, and big memories.' },
  { day: '2025-07-21',  line: 'Her day, her dress, and an apology he still means.' },
  { day: '2025-08-03',  line: 'Waves, sand, and a birthday trip for two.' },
  { day: '2025-10-12',  line: 'Season two of garba. The chemistry is sold out again.' },
  { day: '2025-11-04',  line: 'Just her. Nothing else needed.' },
  { day: '2026-02-14',  line: 'A letter that stays framed in his heart.' },
  { day: '2026-03-21',  line: 'Candlelight, sushi, and one of their best dates ever.' },
  { day: '2026-04-02',  line: 'A new look, and the scene stealer of the season.' },
  { day: '2026-04-23',  line: 'Not goodbye. Just an intermission.' },
  { day: '2026-04-25',  line: 'New colour, same girl.' },
  { day: '2026-05-27',  line: 'Forests, lakes, and a solo adventure.' },
  { day: '2026-07-21',  line: 'Miles apart, and still the best day of the year.' },
  { day: '2026-09-17',  line: 'Water so clear you can count the stones.' },
  { day: '2026-09-23',  line: 'A new city, the same story.' },
  { day: '2026-09-24',  line: 'Umbrella Street, old stone lanes, and a leading lady.' },
  { day: '2026-09-25',  line: 'The last day of the trip, with a first-class view.' },
  { day: '2026-09-26',  line: 'Roses again, goodbye again. The story isn\'t over.' },
];

/* Title treatments — each episode title borrows the lettering of the show it riffs on.
   Keys are episode or season titles; values are the styles in css/app.css (.look-…). */
window.TITLE_LOOKS = {
  'Stranger Things': 'stranger',
  'Om Shanti Om': 'bolly',
  'Happy New Year': 'bollymod',
  'Red Notice': 'heist',
  'Stranger Things Have Happened': 'stranger',
  'Squid Game: CNE Edition': 'squid',
  'Money Heist': 'heist',
  'Lift': 'heist',
  'The Crown': 'crown',
  'The Crown Years': 'crown',
  'Heeramandi': 'crown',
  'Peaky Slippers': 'engraved',
  'The Politician': 'engraved',
  'Bridgerton': 'regency',
  'Made in Heaven: Navratri': 'regency',
  'Made in Heaven, Season 2': 'regency',
  'Indian Matchmaking': 'regency',
  'Dark': 'dark',
  'Origins': 'dark',
  'Our Planet': 'dark',
  'Missing You': 'dark',
  'Next in Fashion': 'dark',
  "The Queen's Gambit": 'gambit',
  'Her Gambit': 'gambit',
  'Emily in Toronto': 'emily',
  'Shivani in Montréal': 'emily',
  'Shivani in Québec': 'emily',
  'Heartstopper': 'hand',
  'Little Things': 'hand',
  'Little Things: Downtown': 'hand',
  'Summertime': 'hand',
  'Outer Banks': 'hand',
  'Somebody Feed Shivani': 'hand',
  'Gilmore Girls': 'gilmore',
  'Drive to Survive': 'drive',
  "Chef's Table: Liu Loqum": 'chef',
  'Selling Sunset': 'chef',
  'Love Is Blind': 'chef',
  'The Circle': 'clean',
  'Too Hot to Handle': 'neon',
  'Glow Up': 'neon',
  'Glow Up, Season 2': 'neon',
  'Fabulous Lives': 'neon',
  'Never Have I Ever': 'playful',
  'Nailed It!': 'playful',
  'Sacred Games': 'sacred',
  'Kuch Kuch Hota Hai': 'bolly',
  'Kabhi Khushi Kabhie Gham': 'bolly',
  'DDLJ': 'bolly',
  'Rab Ne Bana Di Jodi': 'bolly',
  'Main Hoon Na': 'bolly',
  'Kabhi Alvida Naa Kehna': 'bolly',
  'Veer-Zaara': 'bolly',
  'Taare Zameen Par': 'bolly',
  'Dil Se': 'bolly',
  'Ae Dil Hai Mushkil': 'bolly',
  'Hum Tum': 'bolly',
  'Chitthi Aayi Hai': 'bolly',
  'Yaadein': 'bolly',
  'Kal Ho Naa Ho': 'bolly',
  'Befikre': 'bollymod',
  'Cocktail': 'bollymod',
  'Bachna Ae Haseeno': 'bollymod',
  'Rocky Aur Rani': 'bollymod',
  'Queen': 'bollymod',
  'Love Aaj Kal': 'bollymod',
  'Zindagi Na Milegi Dobara': 'bollymod',
  'Yeh Jawaani Hai Deewani': 'bollymod',
  'Dil Chahta Hai': 'bollymod',
  'Dear Zindagi': 'bollymod',
  'Wake Up Shivani': 'bollymod',
  'Dhoom': 'dhoom',
};

/* Love notes — keyed by date (YYYY-MM-DD). An envelope appears on that episode;
   tapping it in the player opens the note as a card. Write as many as you like. */
window.LOVE_NOTES = {
  '2026-04-23': 'The last day before I left Canada. The photo I cherish the most. — Premal',
};

/* "Coming Soon" row */
window.COMING_SOON = [
  { title: 'Season 6', name: 'Long Distance', tag: 'Coming soon',
    blurb: 'Two cities, one story. The next season starts the day Premal leaves Canada.',
    still: 'images/20260423_171132.jpg' },
];

/* Profiles on the "Who's watching?" screen */
window.PROFILES = [
  { name: 'Shivani ♡', photo: 'images/t/20250721_151523.jpg', greeting: 'Welcome back, Shivani. Your story is ready.' },
  { name: 'Premal',    photo: 'images/art/avatar-premal.webp', greeting: 'Welcome back, Premal.' },
];

/* Seasons — every photo/video is placed by its capture date (local Toronto time).
   `from`/`to` are inclusive YYYY-MM-DD. */
window.SEASONS = [
  { n: 0, slug: 's0', title: 'Origins',          from: '2000-01-01', to: '2024-08-19',
    tag: 'Prequel', blurb: 'Before there was an "us", there were these days. The ones we didn\'t know were the beginning.',
    hero: 'images/s_20231021_171309_1.jpg' },
  { n: 1, slug: 's1', title: 'Stranger Things Have Happened',      from: '2024-08-20', to: '2024-09-30',
    tag: 'Aug – Sep 2024', blurb: 'A temple, a first date at Liu Loqum Atelier, and the moment it all started.',
    hero: 'images/20240930_174109.jpg' },
  { n: 2, slug: 's2', title: 'The Crown Years',   from: '2024-10-01', to: '2024-12-31',
    tag: 'Oct – Dec 2024', blurb: 'Navratri nights, her first car, and date nights at the Fairmont.',
    hero: 'images/20241215_002835.jpg' },
  { n: 3, slug: 's3', title: 'Her Gambit',   from: '2025-01-01', to: '2025-06-30',
    tag: 'Jan – Jun 2025', blurb: 'An airport reunion with roses, Planta, Pai Thai — and the day she graduated.',
    hero: 'images/20250412_231204.jpg' },
  { n: 4, slug: 's4', title: 'Kal Ho Naa Ho',      from: '2025-07-01', to: '2026-04-23',
    tag: 'Jul 2025 – Apr 2026', blurb: 'Her birthday, Crystal Beach, Navratri again, a letter, a haircut, and the hardest goodbye.',
    hero: 'images/20250803_194808.jpg' },
  { n: 5, slug: 's5', title: 'To Be Continued…',           from: '2026-04-24', to: '2027-12-31',
    tag: 'Apr 2026 →', blurb: 'Different time zones, a summer back together, her Québec trip, and one more goodbye. Distance is just geography.',
    hero: 'images/s_20260721_145211_1.jpg', toBeContinued: true },
];

/* Per-photo captions, keyed by the media file name, written in Netflix's synopsis voice
   (present tense, third person). Premal's own letters stay in his voice.
   An episode's caption in EPISODE_NOTES wins over these. */
window.STORIES = {
  '20240826_182222.jpg':"Shivani and Premal visit a temple together for the first time.",
  '20240826_182223.jpg':"Shivani and Premal visit a temple together for the first time.",
  '20240826_182226.jpg':"Shivani and Premal visit a temple together for the first time.",
  'Snapchat-1409371325.jpg':"Shivani and Premal visit a temple together for the first time.",
  '20240930_174104.jpg':"Their very first date, at Liu Loqum Atelier on College Street.",
  '20240930_174105.jpg':"Their very first date, at Liu Loqum Atelier on College Street.",
  '20240930_174109.jpg':"Their very first date, at Liu Loqum Atelier on College Street.",
  '20241012_012640.jpg':"Cocktails and a late night at BarChef Toronto.",
  '20241012_012827.jpg':"Cocktails and a late night at BarChef Toronto.",
  '20241012_021256.jpg':"Cocktails and a late night at BarChef Toronto.",
  '20241012_021345.jpg':"Cocktails and a late night at BarChef Toronto.",
  '20241012_021837.jpg':"Cocktails and a late night at BarChef Toronto.",
  '20241014_214812.jpg':"Their first Navratri together, dancing garba to Atul Purohit.",
  '20241014_214813.jpg':"Their first Navratri together, dancing garba to Atul Purohit.",
  '20241014_214823.jpg':"Their first Navratri together, dancing garba to Atul Purohit.",
  '20241014_214824.jpg':"Their first Navratri together, dancing garba to Atul Purohit.",
  'Snapchat-1006342143.jpg':"One more night of garba before the festival ends.",
  'Snapchat-2117433068.jpg':"One more night of garba before the festival ends.",
  '20241103_211756.jpg':"Shivani buys her first car, all by herself.",
  '20241103_211837.jpg':"Shivani buys her first car, all by herself.",
  'IMG_20241120_162835_667.jpg':"A random weekday spent wandering downtown together.",
  'Snapchat-552263264.jpg':"A random weekday spent wandering downtown together.",
  '20241214_233307.jpg':"Drinks at the Clockwork bar inside the Fairmont Royal York.",
  '20241214_233522.jpg':"Drinks at the Clockwork bar inside the Fairmont Royal York.",
  '20241215_002835.jpg':"A night out exploring the city together.",
  '20241215_003011.jpg':"A night out exploring the city together.",
  '20241215_003041.jpg':"A night out exploring the city together.",
  '20241215_003130.jpg':"A night out exploring the city together.",
  '20241215_003241.jpg':"A night out exploring the city together.",
  '20241215_003304.jpg':"A night out exploring the city together.",
  'IMG_20250105_232702_246.jpg':"Premal at Niagara Falls on a cold January day.",
  'Snapchat-1433906752.jpg':"Shivani flies back from India. Premal is waiting at the airport with roses.",
  '20250207_233941.jpg':"One of the good ones. Dinner downtown, and she doesn't stop smiling all night.",
  '20250207_234003.jpg':"One of the good ones. Dinner downtown, and she doesn't stop smiling all night.",
  '20250207_234008.jpg':"One of the good ones. Dinner downtown, and she doesn't stop smiling all night.",
  '20250207_234919.jpg':"One of the good ones. Dinner downtown, and she doesn't stop smiling all night.",
  '20250207_234924.jpg':"One of the good ones. Dinner downtown, and she doesn't stop smiling all night.",
  '20250207_234928.jpg':"One of the good ones. Dinner downtown, and she doesn't stop smiling all night.",
  '20250208_000143.jpg':"One of the good ones. Dinner downtown, and she doesn't stop smiling all night.",
  'valentine.jpg':"Her Valentine's Day letter to me. A note I will keep forever.",
  '20250215_172023.jpg':"A slow afternoon at Eataly at the Shops at Don Mills.",
  'Snapchat-1945727858.jpg':"Home. Just the two of them, being them.",
  'Snapchat-1960320966.jpg':"Home. Just the two of them, being them.",
  '20250412_230943.jpg':"Dinner at Planta Queen. Good food, better company, and a date neither of them wants to end.",
  '20250412_231012.jpg':"Dinner at Planta Queen. Good food, better company, and a date neither of them wants to end.",
  '20250412_231015.jpg':"Dinner at Planta Queen. Good food, better company, and a date neither of them wants to end.",
  '20250412_231130.jpg':"Dinner at Planta Queen. Good food, better company, and a date neither of them wants to end.",
  '20250412_231133.jpg':"Dinner at Planta Queen. Good food, better company, and a date neither of them wants to end.",
  '20250412_231204.jpg':"Dinner at Planta Queen. Good food, better company, and a date neither of them wants to end.",
  '20250426_190640.jpg':"Pai Thai uptown, sharing plates and stealing bites off each other's.",
  '20250426_221747.jpg':"Pai Thai uptown, sharing plates and stealing bites off each other's.",
  '20250426_221751.jpg':"Pai Thai uptown, sharing plates and stealing bites off each other's.",
  '20250426_221755.jpg':"Pai Thai uptown, sharing plates and stealing bites off each other's.",
  '20250426_221758.jpg':"Pai Thai uptown, sharing plates and stealing bites off each other's.",
  '20250426_223101.jpg':"Pai Thai uptown, sharing plates and stealing bites off each other's.",
  '20250521_144010.jpg':"Premal surprises Shivani at work.",
  '20250523_220814.jpg':"Dinner at Piano Piano. She looks unreal tonight, and he can't stop telling her.",
  '20250527_182137.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  '20250527_182725.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  '20250527_182726.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  '20250527_182736.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  '20250527_182738.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  '20250527_182746.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  'Snapchat-1274994827.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  'Snapchat-1963777634.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  'Snapchat-524185506.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  'Snapchat-687287911.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  'Snapchat-790482175.jpg':"Shivani graduates from Northeastern University. Premal has never been prouder.",
  '20250629_151249.jpg':"Pizza at Badiali, with Shivani looking far too good for a pizza place.",
  '20250629_151320.jpg':"Pizza at Badiali, with Shivani looking far too good for a pizza place.",
  '20250629_151405.jpg':"Pizza at Badiali, with Shivani looking far too good for a pizza place.",
  '20250629_151406.jpg':"Pizza at Badiali, with Shivani looking far too good for a pizza place.",
  '20250629_151523.jpg':"Pizza at Badiali, with Shivani looking far too good for a pizza place.",
  '20250706_141011.jpg':"Sandwiches at Alfie's, then a long walk along the Etobicoke lakeshore.",
  '20250706_151749.jpg':"A long walk along the Etobicoke lakeshore. A perfect day, with the perfect person.",
  '20250706_151818.jpg':"A long walk along the Etobicoke lakeshore. A perfect day, with the perfect person.",
  '20250706_151820.jpg':"A long walk along the Etobicoke lakeshore. A perfect day, with the perfect person.",
  '20250706_151912.jpg':"A long walk along the Etobicoke lakeshore. A perfect day, with the perfect person.",
  '20250712_202435.jpg':"Drinks at the Lobby Bar in Elora.",
  '20250712_202440.jpg':"Drinks at the Lobby Bar in Elora.",
  '20250721_151523.jpg':"Shivani's birthday, in the dress Premal gave her.",
  '20250721_220526.jpg':"Cactus Club, Yonge and Sheppard. I'm sorry that day wasn't what you deserved, Shivani.",
  '20250721_220529.jpg':"Shivani's birthday.",
  '20250721_220605.jpg':"Shivani's birthday.",
  '20250721_220615.jpg':"Shivani's birthday.",
  '20250727_201741.jpg':"A random Sunday, just the two of them.",
  '20250727_201742.jpg':"A random Sunday, just the two of them.",
  '20250803_194524.jpg':"Premal's birthday trip, together at Crystal Beach.",
  '20250803_194526.jpg':"Premal's birthday trip, together at Crystal Beach.",
  '20250803_194808.jpg':"Premal's birthday trip, together at Crystal Beach.",
  '20251011_223537.jpg':"Navratri again, and this time it already feels like tradition.",
  '20251011_223614.jpg':"Navratri again, and this time it already feels like tradition.",
  '20251011_223618.jpg':"Navratri again, and this time it already feels like tradition.",
  '20251011_223639.jpg':"Navratri again, and this time it already feels like tradition.",
  'IMG_20251012_172701_525.jpg':"Navratri again, and this time it already feels like tradition.",
  'IMG_20251012_172719_495.jpg':"Navratri again, and this time it already feels like tradition.",
  'IMG_20251012_172727_997.jpg':"Navratri again, and this time it already feels like tradition.",
  'IMG_20251012_172731_352.jpg':"Navratri again, and this time it already feels like tradition.",
  'Snapchat-1884807469.jpg':"Navratri again, and this time it already feels like tradition.",
  'Snapchat-10814446.jpg':"Shivani, just being Shivani. Premal's favourite thing to look at.",
  'Snapchat-1605463310.jpg':"Shivani, just being Shivani. Premal's favourite thing to look at.",
  'Screenshot_20260221_202434_Instagram.jpg':"An old photo I keep coming back to.",
  '20260402_145233.jpg':"Shivani gets her bob. It suits her perfectly, and she loves it this way.",
  '20260402_145240.jpg':"Shivani gets her bob. It suits her perfectly, and she loves it this way.",
  'Snapchat-1282282821.jpg':"Shivani gets her bob. It suits her perfectly, and she loves it this way.",
  '20260423_171132.jpg':"The last day before I left Canada. The photo I cherish the most.",
};

/* Episode notes — keyed by date (YYYY-MM-DD). Fill these in for the new photos:
     '2023-09-23': { title: 'Where it started', story: 'The first time we…', thumb: 'file.jpg' },
   `title` names the episode; `story` shows under every photo of that day;
   `thumb` (optional) is the media file name to use as the episode's cover;
   `merge: 'next' | 'prev'` folds that day into the neighbouring episode. */
window.EPISODE_NOTES = {
  // ── Season 0 · Before Us
  '2023-12-03': { title: 'Cocktail', story: 'A Toronto bar with every wall covered in pictures, and the best one standing in front of them.', thumb: 's_20231203_215002_1.jpg' },
  '2023-12-31': { title: 'Kabhi Khushi Kabhie Gham', story: 'Shivani rings in the new year at her brother\'s restaurant. It\'s all about loving your family.', thumb: 's_20231231_210401_1.jpg' },
  '2024-05-11': { title: 'Selling Sunset', story: 'Dinner at Louix Louis, high above the city at the St. Regis. Very Selling Sunset.', thumb: 's_20240511_000600_1.jpg' },
  '2024-07-21': { title: 'Befikre', story: 'Her birthday, in front of the flower wall at Befikr. Carefree, just like the name says.' },
  '2024-05-20': { title: 'Summertime', story: 'A blue top, a bluer sky, and summer arriving early.', thumb: 's_20240520_161758_1.jpg' },
  '2023-11-03': { title: 'Fabulous Lives', story: 'Seven mirror clips, zero bad angles. The fabulous life, fully documented.', thumb: 's_20231103_185218_1.mp4' },
  '2023-10-22': { title: 'Om Shanti Om', story: 'Gold walls, a golden bar and a black dress. The night after Stranger Things looked like a film set.' },
  '2023-10-21': { title: 'Stranger Things', story: 'A neon sign that says Eleven, a black dress and a bunch of balloons. Stranger things have happened.', thumb: 's_20231021_172016_1.jpg' },
  '2023-12-09': { title: 'Heeramandi', story: 'Chandeliers, marble floors and a princess in black. Bhansali would approve.', thumb: 's_20231209_211928_1.jpg' },
  '2024-06-10': { title: 'The Circle', story: 'Selfie after selfie. She would win The Circle without trying.', thumb: 's_20240610_193550_1.jpg' },
  '2024-03-15': { title: 'Kuch Kuch Hota Hai', story: 'All in white at a flower-filled café, with spring just around the corner. Kuch kuch hota hai.', thumb: 's_20240315_234335_1.jpg' },
  // ── Season 1 · The Beginning
  '2024-08-25': { title: 'Squid Game: CNE Edition', story: 'Rides, lights and carnival games at the CNE. Nobody gets eliminated.', thumb: 's_20240825_120000_1.jpg' },
  '2024-08-26': { title: 'Sacred Games', story: 'Two people, one temple, and the first prayer they share.', thumb: '20240826_182222.jpg' },
  '2024-09-30': { title: 'Chef\'s Table: Liu Loqum', story: 'One latte, one slice of cake, and the only critic who matters is sitting across the table.' },
  // ── Season 2 · Growing Together
  '2024-10-12': { title: 'Money Heist', story: 'The plan: cocktails in smoke at BarChef. The real heist: her heart.' },
  '2024-10-14': { title: 'Made in Heaven: Navratri', story: 'Dhol, dandiya, and two people who keep finding each other in the crowd.' },
  '2024-10-18': { title: 'Rab Ne Bana Di Jodi', story: 'One more night of garba, and the jodi everyone notices.' },
  '2024-11-03': { title: 'Drive to Survive', story: 'Season premiere. One driver, one brand-new car, zero help needed.' },
  '2024-11-20': { title: 'Little Things: Downtown', story: 'A random weekday spent wandering downtown together. It is the little things.' },
  '2024-12-14': { title: 'The Crown', story: 'A royal date at the Royal York. Her Majesty orders the cocktail.' },
  '2024-12-15': { title: 'Taare Zameen Par', story: 'A night out under a window full of stars. Taare zameen par.' },
  // ── Season 3 · Her Biggest Year
  '2025-01-01': { title: 'Happy New Year', story: 'A party hat, a glitter cup and the first hours of 2025. She rang it in like the lead of a Shah Rukh Khan film.' },
  '2025-01-05': { title: 'Missing You', story: 'Premal at Niagara Falls on a cold January day, missing her more than he notices the view.' },
  '2025-01-09': { title: 'Indian Matchmaking', story: 'Shivani is home in Mumbai, at Bastian. Sima Aunty would approve of the outfit.' },
  '2025-01-25': { title: 'Love Is Blind', story: 'Not at Arrivals. He would spot her in any crowd, roses in hand.' },
  '2025-02-07': { title: 'Never Have I Ever', story: 'Never have I ever seen her stop smiling. Still haven\'t.' },
  '2025-02-08': { merge: 'prev' },
  '2025-02-15': { title: 'Somebody Feed Shivani', story: 'A slow afternoon at Eataly, and a plate of pasta that disappears fast.' },
  '2025-04-05': { title: 'Hum Tum', story: 'Home. Just the two of them, being them.' },
  '2025-04-12': { title: 'Rocky Aur Rani', story: 'Dinner at Planta Queen. Good food, better company, and a date neither of them wants to end.' },
  '2025-04-26': { title: 'Nailed It!', story: 'The pad thai: nailed it. Staying awake through dinner: not so much.' },
  '2025-05-21': { title: 'Main Hoon Na', story: 'Premal surprises Shivani at work. Main hoon na.' },
  '2025-05-23': { title: 'Dhoom', story: 'Dinner at Piano Piano. She looks unreal tonight, and he can\'t stop telling her.' },
  '2025-05-27': { title: 'The Queen\'s Gambit', story: 'Every move calculated. Checkmate, Northeastern. Premal has never been prouder.' },
  '2025-06-29': { title: 'Bachna Ae Haseeno', story: 'Pizza at Badiali, with Shivani looking far too good for a pizza place.' },
  // ── Season 4 · One Full Year
  '2025-07-06': { title: 'Heartstopper', story: 'Sandwiches at Alfie\'s, then a long walk along the Etobicoke lakeshore. A perfect day, with the perfect person.' },
  '2025-07-12': { title: 'Gilmore Girls', story: 'A small town, a pink drink, and the coziest scene of the season.' },
  '2025-07-21': { title: 'Dil Se', story: 'Shivani\'s birthday, in the dress Premal gave her. The day doesn\'t go the way she deserves, and he is still sorry, dil se.' },
  '2025-07-27': { title: 'Lift', story: 'A mirror, an elevator, and just the two of them going up.' },
  '2025-08-03': { title: 'Outer Banks', story: 'Sun, sand, and Premal\'s birthday trip to Crystal Beach, for two.' },
  '2025-10-11': { merge: 'next' },
  '2025-10-12': { title: 'Made in Heaven, Season 2', story: 'Navratri again, and this time it already feels like tradition.' },
  '2025-11-04': { title: 'Ae Dil Hai Mushkil', story: 'Shivani, carefree at the Befikr wall. Ae dil hai mushkil to look anywhere else.' },
  '2026-02-14': { title: 'Chitthi Aayi Hai', story: 'Her Valentine\'s Day letter to me. A note I will keep forever.' },
  '2026-02-21': { title: 'Yaadein', story: 'An old photo I keep coming back to.' },
  '2026-03-21': { title: 'Bridgerton', story: 'Candlelight, sushi at Nobu, and the season\'s most talked-about date.' },
  '2026-04-02': { title: 'Glow Up', story: 'Shivani gets her bob. The transformation of the season, and the judges are unanimous.' },
  '2026-04-23': { title: 'Dark', story: 'The last day before I left Canada. Not goodbye, just a different timeline.' },
  // ── Season 5 · Still Us
  '2026-04-25': { title: 'Glow Up, Season 2', story: 'A soft balayage. The glow-up continues.' },
  '2026-05-27': { title: 'Queen', story: 'Shivani\'s solo trip to Algonquin Park. Pure Queen energy.' },
  '2026-06-06': { merge: 'next' },
  '2026-07-21': { title: 'Dear Zindagi', story: 'Her birthday, miles apart, and still the best day of the year.', thumb: 's_20260721_145211_1.jpg' },
  '2026-08-26': { title: 'Red Notice', story: 'Golden hour, a red shirt, and a parking lot that turned into a runway.' },
  '2026-09-16': { merge: 'next' },
  '2026-09-17': { title: 'Our Planet', story: 'The clearest water in Ontario, and a rare sighting: Shivani on a hike.' },
  '2026-09-23': { title: 'Shivani in Montréal', story: 'Day one of the Québec trip, with the whole city below her.', thumb: 's_20260923_120000_3.jpg' },
  '2026-09-24': { title: 'Shivani in Québec', story: 'Umbrella Street, the Château Frontenac and Montmorency Falls. A wardrobe that belongs on a runway.', thumb: 's_20260924_120000_11.jpg' },
  '2026-09-25': { title: 'Yeh Jawaani Hai Deewani', story: 'The last day of the trip: lakes, lookouts, and a view straight out of a movie.' },
  '2026-09-26': { title: 'Kabhi Alvida Naa Kehna', story: 'Roses again, before Premal leaves Canada on September 27. Never say goodbye.', thumb: 's_20260926_120000_1.jpg' },
  '2023-09-23': { title: 'Dil Chahta Hai', story: 'Friends, a long table and a night out in Toronto. Season zero begins the way every great story does: with no idea what is coming.' },
  '2023-09-30': { title: 'Emily in Toronto', story: 'A late walk past glowing shopfronts, dressed like the city is her runway.' },
  '2023-10-04': { title: 'Next in Fashion', story: 'Three takes in the closet mirror. The judges approve every look.' },
  '2023-10-07': { title: 'Little Things', story: 'Sunlight in her hair and a selfie on the road. It is always the little things.' },
  '2023-10-08': { title: 'Wake Up Shivani', story: 'A lazy Sunday, a soft morning, and a camera that clearly loves her.' },
  '2024-06-20': { title: 'The Politician', story: 'An orange dress in front of Old City Hall. The vote is unanimous.' },
  '2024-09-01': { title: 'DDLJ', story: 'A yellow dress, the city lights, and a full Simran moment by the railing.' },
  '2024-11-02': { title: 'Too Hot to Handle', story: 'Twenty-eight photos in one day. Too hot to handle, too pretty to stop.' },
  '2025-05-11': { title: 'Peaky Slippers', story: 'A pair of very fluffy slippers gets a scene of its own.' },
  '2026-06-23': { title: 'Love Aaj Kal', story: 'Long distance, one flying kiss at a time.' },
  '2026-06-24': { title: 'Veer-Zaara', story: 'A pink shirt and a quiet day, sent across the miles.' },
  '2026-09-22': { title: 'Zindagi Na Milegi Dobara', story: 'Window seat, open road, and the start of a road trip she will never forget.', thumb: 's_20260922_191542_1.jpg' },
};

/* Top 10 Moments — in order. Media keys (file names). */
window.TOP10 = [
  '20260423_171132.jpg',   // the last day
  'valentine.jpg',         // her letter
  '20240930_174104.jpg',   // first date
  '20240826_182222.jpg',   // first temple
  '20250527_182736.jpg',   // graduation
  'Snapchat-1433906752.jpg', // airport, roses
  '20250803_194808.jpg',   // crystal beach
  '20250721_151523.jpg',   // birthday dress
  's_20260924_120000_11.jpg', // umbrella street, Québec
  's_20260926_120000_1.jpg',  // roses, the night before
];

/* End credits — in chronological order. */
window.CREDITS = [
  ['Directed by',          'God & the universe'],
  ['Starring',             'Shivani ♡ · Premal'],
  ['',                     ''],
  ['Before us',            'Toronto, 2023'],
  ['Louix Louis',          'May 2024'],
  ['Her birthday, 2024',   'Jul 21, 2024'],
  ['The CNE',              'Aug 25, 2024'],
  ['First temple visit',   'Aug 26, 2024'],
  ['First date',           'Liu Loqum Atelier'],
  ['BarChef Toronto',      'Oct 12, 2024'],
  ['First Navratri',       'Oct 14, 2024'],
  ['Her first car',        'All by herself'],
  ['Clockwork',            'Fairmont Royal York'],
  ['Airport reunion',      'With roses'],
  ['Cactus Club',          'Feb 2025'],
  ["Valentine's note",     'Kept forever'],
  ['Planta Queen',         'Apr 2025'],
  ['Pai',                  'Apr 2025'],
  ['Piano Piano',          'May 2025'],
  ['Her graduation',       'May 27, 2025'],
  ['Badiali',              'Jun 2025'],
  ['The lakeshore',        'Jul 2025'],
  ['Elora',                'Jul 2025'],
  ['Her birthday',         'Jul 21, 2025'],
  ['A birthday apology',   "I'm sorry, Shivani"],
  ['Crystal Beach',        'My birthday trip'],
  ['Navratri 2025',        'Together again'],
  ['The bob haircut',      'Apr 2, 2026'],
  ['Nobu',                 'Mar 21, 2026'],
  ['The hardest goodbye',  'Apr 23, 2026'],
  ['Her birthday, 2026',   'Jul 21, 2026'],
  ['Bruce Peninsula',      'Sep 17, 2026'],
  ['Her Québec trip',      'Sep 23 – 25, 2026'],
  ['Roses, again',         'Sep 26, 2026'],
  ['Another goodbye',      'Sep 27, 2026'],
  ['Still us',             'Every day since'],
  ['',                     ''],
  ['Soundtrack',           'Beete Lamhein'],
  ['Location',             'Toronto, mostly'],
  ['Shot on',              'Our camera rolls'],
  ['Written by',           'Every day together'],
  ['Executive producer',   'Fate'],
  ['',                     ''],
  ['To Shivani',           'my favourite person'],
  ['',                     '— Premal ♡'],
];

window.FINALE = {
  line1: 'To Shivani',
  line2: 'you are my favourite person in the world',
  sign:  '— Premal ♡',
  audio: 'audio/Beete Lamhein The Train 320 Kbps.mp3',
  audioStart: 47,
};
