"""Build the generated title logos and site artwork.

Usage: python3 tools/build_art.py <folder of images downloaded from Drive "Site Art">

Logos: the black background is keyed out (luminance becomes alpha, colour is
un-premultiplied so glows keep their colour), trimmed, and saved as WebP with
alpha. Artwork is resized and saved as WebP. Writes js/art.js.
"""
import json, os, sys
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1]
OUT_LOGO = os.path.join(ROOT, 'images', 'logos')
OUT_ART = os.path.join(ROOT, 'images', 'art')

# Drive file stem (as generated by Flow) → title it renders
LOGOS = {
    'Title_logo_lettering_Shivani_and_': 'Shivani & Premal',
    'Logo_lettering_Origins_displayed': 'Origins',
    'Stranger_Things_Have_Happened_logo': 'Stranger Things Have Happened',
    'The_Crown_Years_logo_lettering': 'The Crown Years',
    'Her_Gambit_logo_lettering': 'Her Gambit',
    'Gold_lettering_reads_Kal_Ho': 'Kal Ho Naa Ho',
    'To_Be_Continued_Lettering': 'To Be Continued…',
    'Stranger_Things_logo_lettering': 'Stranger Things',
    'Squid_Game_CNE_Edition_logo': 'Squid Game: CNE Edition',
    'Money_Heist_logo_lettering': 'Money Heist',
    'Red_Lift_logo_lettering': 'Lift',
    'The_Crown_logo_lettering': 'The Crown',
    'Heeramandi_gold_title_logo': 'Heeramandi',
    'Peaky_Slippers_logo_lettering': 'Peaky Slippers',
    'Logo_lettering_reading_The_Polit_': 'The Politician',
    'Bridgerton_title_logo_lettering': 'Bridgerton',
    'Logo_lettering_Made_in_Heaven_2': 'Made in Heaven: Navratri',
    'Logo_lettering_Made_in_Heaven': 'Made in Heaven, Season 2',
    'Indian_Matchmaking_logo_lettering': 'Indian Matchmaking',
    'Lettering_reading_Dark': 'Dark',
    'Our_Planet_logo_lettering': 'Our Planet',
    'Missing_You_title_lettering': 'Missing You',
    'Logo_lettering_Next_in_Fashion': 'Next in Fashion',
    'The_Queen_s_Gambit_logo': "The Queen's Gambit",
    'Emily_in_Toronto_lettering_logo': 'Emily in Toronto',
    'Shivani_in_Montr_al_logo_lettering': 'Shivani in Montréal',
    'Shivani_in_Quebec_lettering_logo': 'Shivani in Québec',
    'Heartstopper_logo_lettering': 'Heartstopper',
    'Lettering_reading_Little_Things': 'Little Things',
    'Little_Things_Downtown_lettering': 'Little Things: Downtown',
    'Summertime_lettering_on_black_ba_': 'Summertime',
    'Outer_Banks_title_logo_lettering': 'Outer Banks',
    'Lettering_reads_Somebody_Feed_Sh_': 'Somebody Feed Shivani',
    'Gilmore_Girls_logo_lettering': 'Gilmore Girls',
    'Drive_to_Survive_logo_lettering': 'Drive to Survive',
    'Chef_s_Table_logo_lettering': "Chef's Table: Liu Loqum",
    'Selling_Sunset_title_logo_lettering': 'Selling Sunset',
    'Love_Is_Blind_logo_lettering': 'Love Is Blind',
    'The_Circle_logo_lettering': 'The Circle',
    'Too_Hot_to_Handle_logo': 'Too Hot to Handle',
    'Glow_Up_lettering_logo': 'Glow Up',
    'Glow_Up_Season_2_logo': 'Glow Up, Season 2',
    'Fabulous_Lives_logo_lettering': 'Fabulous Lives',
    'Lettering_reads_Never_Have_I': 'Never Have I Ever',
    'Logo_lettering_reads_Nailed_It': 'Nailed It!',
    'Sacred_Games_title_logo_lettering': 'Sacred Games',
    'Kuch_Kuch_Hota_Hai_lettering': 'Kuch Kuch Hota Hai',
    'Kabhi_Khushi_Kabhie_Gham_lettering': 'Kabhi Khushi Kabhie Gham',
    'DDLJ_title_logo_lettering': 'DDLJ',
    'Rab_Ne_Bana_Di_Jodi': 'Rab Ne Bana Di Jodi',
    'Main_Hoon_Na_logo_lettering': 'Main Hoon Na',
    'Title_logo_letteringKabhi_Alvida_': 'Kabhi Alvida Naa Kehna',
    'Veer-Zaara_title_logo_lettering': 'Veer-Zaara',
    'Taare_Zameen_Par_logo_lettering': 'Taare Zameen Par',
    'Dil_Se_logo_lettering': 'Dil Se',
    'Ae_Dil_Hai_Mushkil_lettering': 'Ae Dil Hai Mushkil',
    'Hum_Tum_logo_lettering': 'Hum Tum',
    'Chitthi_Aayi_Hai_logo_lettering': 'Chitthi Aayi Hai',
    'Yaadein_logo_lettering_on_black': 'Yaadein',
    'Befikre_logo_lettering': 'Befikre',
    'Cocktail_neon_sign_lettering': 'Cocktail',
    'Bachna_Ae_Haseeno_logo_lettering': 'Bachna Ae Haseeno',
    'Rocky_Aur_Rani_logo_lettering': 'Rocky Aur Rani',
    'Queen_lettering_logo': 'Queen',
    'Love_Aaj_Kal_logo_lettering': 'Love Aaj Kal',
    'Zindagi_Na_Milegi_Dobara_lettering': 'Zindagi Na Milegi Dobara',
    'Yeh_Jawaani_Hai_Deewani_lettering': 'Yeh Jawaani Hai Deewani',
    'Dil_Chahta_Hai_title_logo': 'Dil Chahta Hai',
    'Wake_Up_Shivani_logo_lettering': 'Wake Up Shivani',
    'Logo_lettering_reading_Dhoom': 'Dhoom',
}
# Logos that sit on an opaque object (envelope, film strip): keep the object solid
SOLID = {'Chitthi Aayi Hai', 'Yaadein'}

# Drive file stem → (key in window.ART, max long side)
ART = {
    'Toronto_skyline_at_night': ('profiles', 1920),
    'Glowing_thread_connecting_two_ci_': ('comingSoon', 1280),
    'Film_strip_light_leaks': ('previously', 1920),
    'Spotlight_beam_with_floating_dust': ('trailer', 1280),
    'Handmade_paper_with_pressed_roses': ('paper', 1200),
    'Empty_cinema_glowing_screen': ('credits', 1920),
    'Golden_fairy_lights_background': ('closing', 1920),
    'Red_Top_10_badge': ('top10', 128),
}

def slug(t):
    return ''.join(c if c.isalnum() else '-' for c in t.lower().replace('&', 'and').replace('é', 'e')).strip('-').replace('--', '-').replace('--', '-')

def key_black(im, solid=False):
    a = np.asarray(im.convert('RGB')).astype(np.float32)
    h, w, _ = a.shape
    lum = a.max(axis=2)
    border = np.concatenate([lum[:h // 12].ravel(), lum[-h // 12:].ravel(), lum[:, :w // 14].ravel(), lum[:, -w // 14:].ravel()])
    floor = min(70.0, np.percentile(border, 99.5) + 6)       # background level (vignettes, haze)
    # anything brighter than ~150 is solid lettering; dimmer pixels are glow and fade out
    alpha = np.clip((lum - floor) / (150 - floor), 0, 1)
    if solid:                                                # opaque prop: anything clearly above the floor is solid
        alpha = np.clip(alpha * 4, 0, 1)
    # un-premultiply against black so glows keep their colour; a solid prop keeps its own
    rgb = a if solid else np.clip(a / np.maximum(alpha[..., None], 1 / 255), 0, 255)
    out = np.dstack([rgb, alpha * 255]).astype(np.uint8)
    ys, xs = np.where(alpha > 0.04)
    pad = 8
    box = (max(xs.min() - pad, 0), max(ys.min() - pad, 0), min(xs.max() + pad, w), min(ys.max() + pad, h))
    return Image.fromarray(out, 'RGBA').crop(box)

def main():
    os.makedirs(OUT_LOGO, exist_ok=True); os.makedirs(OUT_ART, exist_ok=True)
    files = {os.path.splitext(f)[0]: os.path.join(SRC, f) for f in os.listdir(SRC)}
    logos, art = {}, {}
    for stem, title in LOGOS.items():
        if stem not in files: print('missing logo', stem); continue
        im = key_black(Image.open(files[stem]), title in SOLID)
        im.thumbnail((720, 300), Image.LANCZOS)
        name = f'{slug(title)}.webp'
        im.save(os.path.join(OUT_LOGO, name), 'WEBP', quality=84, alpha_quality=80, method=4)
        logos[title] = {'f': f'images/logos/{name}', 'w': im.width, 'h': im.height}
    for stem, (k, size) in ART.items():
        if stem not in files: print('missing art', stem); continue
        im = Image.open(files[stem]).convert('RGB')
        if k == 'top10':
            im = im.crop(red_box(im))
        if k == 'paper':                                     # just the sheet, inside its deckled edge
            W, H = im.size; im = im.crop((int(W * .15), int(H * .125), int(W * .88), int(H * .885)))
        im.thumbnail((size, size), Image.LANCZOS)
        name = f'{k}.webp'
        im.save(os.path.join(OUT_ART, name), 'WEBP', quality=82, method=4)
        art[k] = f'images/art/{name}'
    # Profile avatars
    for stem, name in (('Blue_profile_avatar_smiling_face', 'avatar-premal'), ('Smiling_face_profile_avatar', 'avatar-shivani')):
        if stem in files:
            im = Image.open(files[stem]).convert('RGB'); im = im.crop(color_box(im))
            im.resize((320, 320), Image.LANCZOS).save(os.path.join(OUT_ART, f'{name}.webp'), 'WEBP', quality=88)
            art[name] = f'images/art/{name}.webp'
    # App icons from the ampersand
    if 'Red_ampersand_app_icon' in files:
        im = Image.open(files['Red_ampersand_app_icon']).convert('RGB'); im = im.crop(color_box(im, red=True))
        for size, path in ((512, 'icon-512.png'), (192, 'icon-192.png'), (180, 'apple-touch-icon.png'), (32, 'favicon-32.png')):
            im.resize((size, size), Image.LANCZOS).save(os.path.join(ROOT, 'icons', path), optimize=True)
    with open(os.path.join(ROOT, 'js', 'art.js'), 'w') as f:
        f.write('/* Generated by tools/build_art.py: title logos (keyed to alpha) and site artwork. */\n')
        f.write('window.LOGOS = ' + json.dumps(logos, ensure_ascii=False, indent=0).replace('\n', '') + ';\n')
        f.write('window.ART = ' + json.dumps(art, indent=0).replace('\n', '') + ';\n')
    print('logos', len(logos), 'art', len(art))

def red_box(im):
    a = np.asarray(im).astype(int); m = (a[..., 0] > 150) & (a[..., 1] < 90)
    ys, xs = np.where(m); return (xs.min(), ys.min(), xs.max() + 1, ys.max() + 1)

def color_box(im, red=False):
    """Square box around the rounded-square tile (the saturated region)."""
    a = np.asarray(im).astype(int)
    sat = a.max(axis=2) - a.min(axis=2)
    m = sat > (90 if red else 70)
    if red: m &= a[..., 0] > 60
    rows, cols = np.where(m.sum(axis=1) > m.shape[1] * 0.25)[0], np.where(m.sum(axis=0) > m.shape[0] * 0.25)[0]
    x0, x1, y0, y1 = cols.min(), cols.max(), rows.min(), rows.max()
    s = max(x1 - x0, y1 - y0); cx, cy = (x0 + x1) // 2, (y0 + y1) // 2
    return (cx - s // 2, cy - s // 2, cx + s // 2, cy + s // 2)

if __name__ == '__main__':
    main()
