"""Score every photo's sharpness (variance of the Laplacian on its 720px thumbnail) -> js/quality.js.
The app uses it to choose covers, Big Moments and billboard photos."""
import json, os, re
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(f'{ROOT}/js/media.js').read()
media = json.loads(src[src.index('['):src.rindex(']') + 1])
q = {}
for m in media:
    if m['k'] != 'img':
        continue
    g = Image.open(os.path.join(ROOT, m['t'])).convert('L'); g.thumbnail((640, 640))
    a = np.asarray(g, dtype=np.float32)
    lap = a[1:-1, 1:-1] * 4 - a[:-2, 1:-1] - a[2:, 1:-1] - a[1:-1, :-2] - a[1:-1, 2:]
    q[m['key']] = round(min(float(lap.var()), 1500) / 300 + 0.2, 2)   # 0.2 .. 5.2
with open(f'{ROOT}/js/quality.js', 'w') as f:
    f.write('/* Generated by tools/score_quality.py: photo sharpness for picking covers. */\n')
    f.write('window.QUALITY = ' + json.dumps(q, separators=(',', ':')) + ';\n')
print(len(q), 'scored')
